name: Docker Image Build & Push

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Docker Build
        run: |
          echo "${{ secrets.DOCKERTOKEN }}" | docker login -u "prathamdh18" --password-stdin
          docker build -t  prathamdh18/fastapi-app:latest .
          docker push  prathamdh18/fastapi-app:latest

